# Generated by Django 2.2.12 on 2020-04-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
