# Generated by Django 2.2.12 on 2020-04-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200421_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='actuality',
            field=models.CharField(choices=[('n', 'New'), ('a', 'Added'), ('s', 'Skipped')], default='', max_length=1),
        ),
    ]
